---
image: docker:cli
services:
  - docker:dind

stages:
  - Checks

.login_into_dockerhub:
  before_script:
    - docker login --username $DOCKERHUB_USER --password $DOCKERHUB_TOKEN

Unit Tests:
  stage: Checks
  extends: .login_into_dockerhub
  script:
    - docker-compose run --rm app sh -c "python manage.py test"

Linting:
  stage: Checks
  extends: .login_into_dockerhub
  script:
    - docker-compose run --rm app sh -c "flake8"
